### ISSUE TITLE
Error during compile

### ISSUE THREAD

**Issue by Ste74** [mate-desktop/libmateweather#48]
Hi there , i 'm considering to update our mate pkgs to last 1.19.x release in our unstable branch ( Manjaro repo ) . Build the pkgs following the build order but libmateweather give me this error 
```

Traceback (most recent call last):
  File "/usr/bin/gtkdoc-rebase", line 56, in <module>
    sys.exit(rebase.run(options))
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 73, in run
    ScanDirectory(dir, options)
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 131, in ScanDirectory
    ScanDirectory(subdir, options)
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 104, in ScanDirectory
    o = ReadDevhelp(scan_dir, entry)
  File "/usr/share/gtk-doc/python/gtkdoc/rebase.py", line 137, in ReadDevhelp
    for line in open(os.path.join(dir, file)):
  File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3734: ordinal not in range(128)
make[2]: *** [Makefile:811: install-data-local] Error 1
make[2]: Leaving directory '/build/libmateweather/src/libmateweather-1.19.1/doc'
make[1]: *** [Makefile:554: install-am] Error 2
make[1]: Leaving directory '/build/libmateweather/src/libmateweather-1.19.1/doc'
make: *** [Makefile:493: install-recursive] Error 1
==> ERROR: A failure occurred in package().
    Aborting...
~/mate >>>
```
I don't understand this error .. what i missing ?

**Comment by sc0w** [comment]
the build is ok here with 1.19.1 in debian testing and I can make .deb packages

**Comment by Ste74** [comment]
This is my pkgbuild grab from arch and modify where needed
```

_ver=1.19
pkgbase=libmateweather
pkgname=(${pkgbase})
pkgver=${_ver}.1
pkgrel=0.1
pkgdesc="Provides access to weather information from the Internet."
url="http://mate-desktop.org"
arch=('i686' 'x86_64')
license=('LGPL')
depends=('gtk3' 'libsoup')
conflicts=("${pkgbase}-gtk3")
replaces=("${pkgbase}-gtk3")
makedepends=('intltool')
source=("http://pub.mate-desktop.org/releases/${_ver}/${pkgname}-${pkgver}.tar.xz")
sha1sums=('c8904ebe570a938180ddab6f0d3eae1fcf376475')

build() {
    cd "${srcdir}/${pkgbase}-$pkgver"
    ./configure \
        --prefix=/usr \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --disable-python \
        --enable-locations-compression

    #https://bugzilla.gnome.org/show_bug.cgi?id=656231
    sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool

    make
}

package() {
    cd "${srcdir}/${pkgbase}-$pkgver"
    make DESTDIR="${pkgdir}" install
}
```

**Comment by monsta** [comment]
I don't know what "gtkdoc-rebase" is, but the log shows that the exception happens in it, not in our library.
