### ISSUE TITLE
Segfault on adding new location to calendar

### ISSUE THREAD

**Issue by lukefromdc** [mate-desktop/libmateweather#75]
#### Expected behaviour
Adding location to calendar works normally

#### Actual behaviour
Panel segfaults on clicking "OK" button in dialog to add location

#### Steps to reproduce the behaviour
Open the calendar popup , it will come up with "locations" selected
click "edit" and then "add" buttons
Select any location
click "OK" and that's when the panel segfaults. When it restarts the location will have been sucessfully added. 
Got this backtrace in gdb

```

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) thread apply all bt full

Thread 6 (Thread 0x7fffdefff700 (LWP 14569)):
#0  0x00007ffff7fe80c5 in  () at /lib64/ld-linux-x86-64.so.2
mate-desktop/mate-panel#1  0x00007ffff6a8db2f in _dl_catch_exception () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#2  0x00007ffff7fe7bba in  () at /lib64/ld-linux-x86-64.so.2
mate-desktop/mate-panel#3  0x00007ffff6a8d06d in  () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#4  0x00007ffff6a8db2f in _dl_catch_exception () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#5  0x00007ffff6a8dbbf in _dl_catch_error () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#6  0x00007ffff6a8d147 in  () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#7  0x00007ffff6a8d1d6 in __libc_dlopen_mode () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#8  0x00007ffff6a74b9e in  () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#9  0x00007ffff6a75498 in __nss_lookup_function () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#10 0x00007ffff6a755b2 in __nss_lookup () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#11 0x00007ffff6a6758b in getservbyname_r () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#12 0x00007ffff6a67173 in getservbyname () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#13 0x00007fffecd288eb in libproxy::url::url(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
mate-desktop/mate-panel#14 0x00007fffecd29029 in libproxy::url::is_valid(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
mate-desktop/mate-panel#15 0x00007fffecd238e2 in  () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
mate-desktop/mate-panel#16 0x00007fffecd23d7d in px_proxy_factory_get_proxies () at /usr/lib/x86_64-linux-gnu/libproxy.so.1
--Type <RET> for more, q to quit, c to continue without paging--
mate-desktop/mate-panel#17 0x00007fffeeee047c in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libgiolibproxy.so
mate-desktop/mate-panel#18 0x00007ffff721ddae in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
mate-desktop/mate-panel#19 0x00007ffff706e0d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#20 0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#21 0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#22 0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 5 (Thread 0x7fffeec6a700 (LWP 14446)):
#0  0x00007ffff6a4cf59 in syscall () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff708f432 in g_cond_wait_until () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff70183e1 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff706e22a in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffef7fe700 (LWP 14445)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff41e0ffd in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.--Type <RET> for more, q to quit, c to continue without paging--
so
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffeffff700 (LWP 14444)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff7281b46 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff4a45700 (LWP 14443)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff7045e61 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 (Thread 0x7ffff5037f00 (LWP 14424)):
#0  0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#1  0x00007ffff713097e in g_object_ref () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff797c05a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
mate-desktop/mate-panel#3  0x00007ffff712c006 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff7147ba0 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7148122 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#6  0x00007ffff7559a9f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
mate-desktop/mate-panel#7  0x00007ffff7544ca8 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
mate-desktop/mate-panel#8  0x00007ffff70464d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#9  0x00007ffff70459fe in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#10 0x00007ffff7045d80 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#11 0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#12 0x00007ffff7844fb5 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
mate-desktop/mate-panel#13 0x00005555555789f1 in main ()
(gdb) 
(gdb) 
(gdb) Quit
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4a45700 (LWP 15614)]
[New Thread 0x7fffeffff700 (LWP 15615)]
[New Thread 0x7fffef7fe700 (LWP 15616)]
[New Thread 0x7fffeec6a700 (LWP 15617)]
[New Thread 0x7fffed149700 (LWP 15650)]
[Thread 0x7fffeec6a700 (LWP 15617) exited]

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007fff00000001 in ?? ()
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4a45700 (LWP 16518)]
[New Thread 0x7fffeffff700 (LWP 16519)]
[New Thread 0x7fffef7fe700 (LWP 16520)]
[New Thread 0x7fffeec6a700 (LWP 16521)]
[New Thread 0x7fffed81b700 (LWP 16537)]
[New Thread 0x7fffdffff700 (LWP 16570)]
[Thread 0x7fffed81b700 (LWP 16537) exited]
[Thread 0x7fffeec6a700 (LWP 16521) exited]
[Thread 0x7fffdffff700 (LWP 16570) exited]
[New Thread 0x7fffdffff700 (LWP 16891)]
[Thread 0x7fffdffff700 (LWP 16891) exited]
[New Thread 0x7fffdffff700 (LWP 17042)]
free(): invalid pointer

Thread 1 "mate-panel" received signal SIGABRT, Aborted.
0x00007ffff69907bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) exit
Undefined command: "exit".  Try "help".
(gdb) quit
A debugging session is active.

	Inferior 1 [process 16517] will be killed.

Quit anyway? (y or n) y
luke@ubuntu:~$ gdb mate-panel
GNU gdb (Debian 8.3-1) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mate-panel...
(gdb) run
Starting program: /usr/bin/mate-panel 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4a45700 (LWP 23898)]
[New Thread 0x7fffeffff700 (LWP 23899)]
[New Thread 0x7fffef7fe700 (LWP 23900)]
[New Thread 0x7fffeec6a700 (LWP 23901)]
[New Thread 0x7fffee469700 (LWP 23902)]
[New Thread 0x7fffec948700 (LWP 23929)]
[Thread 0x7fffeec6a700 (LWP 23901) exited]
[Thread 0x7fffee469700 (LWP 23902) exited]
[New Thread 0x7fffee469700 (LWP 23996)]
[Thread 0x7fffec948700 (LWP 23929) exited]

Thread 1 "mate-panel" received signal SIGSEGV, Segmentation fault.
0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) thread apply all bt full

Thread 8 (Thread 0x7fffee469700 (LWP 23996)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff58c8207 in  () at /lib/x86_64-linux-gnu/libresolv.so.2
mate-desktop/mate-panel#2  0x00007ffff58c5c43 in __res_context_query () at /lib/x86_64-linux-gnu/libresolv.so.2
mate-desktop/mate-panel#3  0x00007ffff58c6286 in  () at /lib/x86_64-linux-gnu/libresolv.so.2
mate-desktop/mate-panel#4  0x00007ffff58c684d in __res_context_search () at /lib/x86_64-linux-gnu/libresolv.so.2
mate-desktop/mate-panel#5  0x00007fffec1430ba in _nss_dns_gethostbyname4_r () at /lib/x86_64-linux-gnu/libnss_dns.so.2
mate-desktop/mate-panel#6  0x00007ffff6a3be0a in  () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#7  0x00007ffff6a3ce37 in getaddrinfo () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#8  0x00007ffff722148d in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
mate-desktop/mate-panel#9  0x00007ffff721ddae in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
mate-desktop/mate-panel#10 0x00007ffff706e0d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#11 0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#12 0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#13 0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 4 (Thread 0x7fffef7fe700 (LWP 23900)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libgl--Type <RET> for more, q to quit, c to continue without paging--
ib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff41e0ffd in  () at /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 3 (Thread 0x7fffeffff700 (LWP 23899)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff7281b46 in  () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7ffff4a45700 (LWP 23898)):
#0  0x00007ffff6a47819 in poll () at /lib/x86_64-linux-gnu/libc.so.6
mate-desktop/mate-panel#1  0x00007ffff7045cee in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff7045e0f in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#3  0x00007ffff7045e61 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff706d9fd in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
--Type <RET> for more, q to quit, c to continue without paging--
mate-desktop/mate-panel#5  0x00007ffff7d5ffa3 in start_thread () at /lib/x86_64-linux-gnu/libpthread.so.0
mate-desktop/mate-panel#6  0x00007ffff6a524cf in clone () at /lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7ffff5037f00 (LWP 23879)):
#0  0x00007ffff714fadd in g_type_check_instance_is_fundamentally_a () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#1  0x00007ffff713097e in g_object_ref () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#2  0x00007ffff797c05a in  () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
mate-desktop/mate-panel#3  0x00007ffff712c006 in  () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#4  0x00007ffff7147ba0 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#5  0x00007ffff7148122 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
mate-desktop/mate-panel#6  0x00007ffff7559a9f in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
mate-desktop/mate-panel#7  0x00007ffff7544ca8 in  () at /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
mate-desktop/mate-panel#8  0x00007ffff70464d4 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#9  0x00007ffff70459fe in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#10 0x00007ffff7045d80 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#11 0x00007ffff7046053 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
mate-desktop/mate-panel#12 0x00007ffff7844fb5 in gtk_main () at /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
mate-desktop/mate-panel#13 0x00005555555789f1 in main (argc=<optimized out>, argv=<optimized out>) at main.c:22--Type <RET> for more, q to quit, c to continue without paging--
7
        desktopfile = <optimized out>
        context = <optimized out>
        error = 0x0
        display = <optimized out>
        screen = 0x55555562a020
        css = 0x555555837040
        provider = 0x555555837040
        resource = 0x5555555c5588 "/org/mate/panel/theme/mate-panel.css"
        priority = 1
        found_backend = <optimized out>
(gdb) 

```
#### MATE general version
1.23 from git master

#### Package version
local build from git master as of 9-11-2019

#### Linux Distribution
Debian Unstable last updated Sep 6

#### Link to downstream report of your Distribution
None as this is a local build

**Comment by kloczek** [comment]
Any plans to make new release?
